version: "3.7"
services:
    app:
        build:
            dockerfile: ./.deploy/Dockerfile
        image: video_streamer_laravel-docker:2.0
        container_name: video_streamer_app
        restart: unless-stopped
        volumes:
            - ./:/src/app
        networks:
            - video_streamer
        ports:
            - '9000:80'

    db:
        image: mysql:latest
        container_name: mysql_video_streamer
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_USER: ${DB_USERNAME}
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        ports:
            - '3306:3306'
        volumes:
            - ./docker-compose/mysql:/docker-entrypoint-initdb.d
        networks:
            - video_streamer

networks:
    video_streamer:
        driver: bridge


