version: "3.7"
services:
    app:
        build:
            context: ./
            dockerfile: Dockerfile
        image: video_streamer_laravel-docker:0.1.1
        container_name: video_streamer_app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - video_streamer

    db:
        image: mysql:latest
        container_name: mysql_video_streamer
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_USER: ${DB_USERNAME}
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - ./docker-compose/mysql:/docker-entrypoint-initdb.d
        networks:
            - video_streamer


    nginx:
        image: nginx:1.17-alpine
        container_name: video_streamer_nginx
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            - ./docker-compose/nginx:/etc/nginx/conf.d
            - ./:/var/www
        networks:
            - video_streamer


networks:
    video_streamer:
        driver: bridge


