version: "3.7"
services:
    app:
        build:
            dockerfile: ./Dockerfile
        image: video-streamer:2
        container_name: video_streamer_app
        restart: unless-stopped
        volumes:
            - "/var/www/html/public/app"
            - "/var/www/html/storage/public"
        networks:
            - video_streamer
        ports:
            - '9000:80'

    db:
        image: mysql:latest
        container_name: mysql_video_streamer
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_USER: ${DB_USERNAME}
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        ports:
            - '3306:3306'
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - video_streamer

networks:
    video_streamer:
        driver: bridge

volumes:
  dbdata:

